### ISSUE TITLE
README update to get around: Error when running pip install -r requirements.txt

### ISSUE THREAD

**Issue by evroom** [schris88/MMM-Hoymiles-Wifi#1]
Hi,

Trying to get your module working.
I am using [hoymiles-wifi](https://github.com/suaveolent/hoymiles-wifi) myself and am curious on how it looks on the MagicMirror.
Nice initiative, but I will open some Issues for you to have a look at, as it is not working according to the README.

First the requirements:

This step is needed to get to the requirements.txt file:
`$ cd MMM-Hoymiles-Wifi`

Then the install fails:
```
admin@BlackPi4b:~/MagicMirror/modules $ cd MMM-Hoymiles-Wifi
admin@BlackPi4b:~/MagicMirror/modules/MMM-Hoymiles-Wifi $ pip install -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
I used this 'workaround' to make it work:
```
$ python3 -m venv env
$ cd env
$ source bin/activate
$ pip3 install -r ~/MagicMirror/modules/MMM-Hoymiles-Wifi/requirements.txt
$ deactivate
```
Not all Python environments are the same.
More workarounds might be available.

Please consider updating the README file.

```
admin@BlackPi4b:~ $ cat /proc/cpuinfo | egrep '^model name|^Hardware|^Revision|^Model' | sort -u
Model		: Raspberry Pi 4 Model B Rev 1.5
Revision	: d03115

admin@BlackPi4b:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

**Comment by schris88** [comment]
1. Yes it depends if you have a full install or used brew for ex., if you want to install them globally you can use "--break-system-packages" like it says in the log. 
2. if you want to use you venv environment make sure to to add the activate in the update.sh before the server starts like you would normally do "source <path to venv/bin/activate> otherwise your installed libs wont be available if you try to run it outside the virtual environment. 
This is a bit off topic because this depends on the python setup

**Comment by evroom** [comment]
Thanks for commenting so fast.

Perhaps you know MMM better than me, but I think that most users are copy/pasters. 
A bit like me, although I know Linux quite well.
And they use various platforms.
So, the README is quite important if you want others to use your module.
Guidance for ‘common’ errors is therefore welcome information.
Not saying that you need to provide error handling for all cases and platforms.
In this case it cannot hurt to have your comment #1 in the README.

Just trying to be constructive :-)

**Comment by evroom** [comment]
Addressed in this fork:
https://github.com/evroom/MMM-Hoymiles-Wifi
